### ISSUE TITLE
Issues in Checkout page

### ISSUE THREAD

**Issue by kish2011** [razorpay/razorpay-edd#13]
![Screenshot 2020-02-10 at 2 21 05 PM](https://user-images.githubusercontent.com/5745798/74134525-bcdcdc00-4c10-11ea-8c57-c4ca28fec1d2.png)

I see this issue once I do a checkout in my EDD store. I am using the latest version of EDD & RazorPay plugin.

**Comment by dbjpanda** [comment]
Same issue here

**Comment by ramth05** [comment]
@kish2011 , can you please provide your site url here to verify the exact issue?

**Comment by kish2011** [comment]
@ramth05 Please try this link https://wpdrift.com/checkout?edd_action=add_to_cart&download_id=3736&edd_options[price_id]=2

**Comment by kish2011** [comment]
Version 2.1.0 I am using.

**Comment by ramth05** [comment]
> @ramth05 Please try this link [https://wpdrift.com/checkout?edd_action=add_to_cart&download_id=3736&edd_options[price_id]=2](https://wpdrift.com/checkout?edd_action=add_to_cart&download_id=3736&edd_options%5Bprice_id%5D=2)

@kish2011 , by looking into it, looks like currency is not setting properly. We will check the thing and get back to you ASAP.

**Comment by ramth05** [comment]
> > @ramth05 Please try this link [https://wpdrift.com/checkout?edd_action=add_to_cart&download_id=3736&edd_options[price_id]=2](https://wpdrift.com/checkout?edd_action=add_to_cart&download_id=3736&edd_options%5Bprice_id%5D=2)
> 
> @kish2011 , by looking into it, looks like currency is not setting properly. We will check the thing and get back to you ASAP.

@kish2011 , Is it possible for you to provide clone/test site of your site for our testing purpose with the details of admin login. you can DM me here  'ramprakash.singh@razorpay.com' .

**Comment by kish2011** [comment]
I can add this email id as admin. ramprakash.singh@

**Comment by kish2011** [comment]
Last time it was the issues https://github.com/razorpay/razorpay-edd/pull/5

**Comment by kish2011** [comment]
looks like it is working now. Have you done something?

**Comment by kish2011** [comment]
Also, does it support easy digital downloads recurring payments https://easydigitaldownloads.com/downloads/recurring-payments/

**Comment by kish2011** [comment]
![payment-declined](https://user-images.githubusercontent.com/5745798/75620747-9cba9000-5bb2-11ea-84f5-cf0e753db0ce.png)

While doing the payment in the end step it says payment declined. @ramth05

**Comment by dbjpanda** [comment]
@ramth05 Can you please provide a general solution for the issue. Or can you tell us what is the issue or which one needs to be tuned to make the plugin worked

**Comment by ramth05** [comment]
> @ramth05 Can you please provide a general solution for the issue. Or can you tell us what is the issue or which one needs to be tuned to make the plugin worked. 

@dbjpanda , looks like some issue with currency settings. Give us sometime to verify the things properly at our end.


> Also, does it support easy digital downloads recurring payments https://easydigitaldownloads.com/downloads/recurring-payments/

@kish2011, No, It's not supporting recurring -payments currently.

**Comment by ramth05** [comment]
> > @ramth05 Can you please provide a general solution for the issue. Or can you tell us what is the issue or which one needs to be tuned to make the plugin worked.
> 
> @dbjpanda , looks like some issue with currency settings. Give us sometime to verify the things properly at our end.
> 
> > Also, does it support easy digital downloads recurring payments https://easydigitaldownloads.com/downloads/recurring-payments/
> 
> @kish2011, No, It's not supporting recurring -payments currently.

@kish2011 @dbjpanda , I have tested the things in your site and this module is working perfectly fine. The only issue is that your API key must support foreign currency. If it's not please ask Razorpay support team to allow it.
