### ISSUE TITLE
openRazorpay is not defined

### ISSUE THREAD

**Issue by dbjpanda** [razorpay/razorpay-edd#14]
Hi,
Even after many time tests, I am getting the same error.
`Uncaught SyntaxError: Invalid or unexpected token`
`checkout?payment-mode=manual:109 Uncaught ReferenceError: openRazorpay is not defined`

Note: I have minutely checked the API Keys.

**Comment by ChetanGN** [comment]
@dbjpanda can you please let me know which version of Razorpay plugin you are using!

**Comment by ChetanGN** [comment]
@dbjpanda  Please try with the latest [plugin](https://github.com/razorpay/razorpay-edd/releases/tag/2.1.0). It's working for WP. Please let us know if you still facing the issue.
