### ISSUE TITLE
Redirect to checkout after successful payment. 

### ISSUE THREAD

**Issue by incrediblenitin** [razorpay/razorpay-edd#6]
Hello,

I am discussing this issue with the tech support at Razorpay but looks like they have no idea about the EDD.

With the latest version of EDD, this plugin does not seem to be working. I've tested with both test and live api keys. **After a successful payment, it is redirecting back to the checkout page with a message saying "payment failed".** 

Thanks and regards,
Nitin.

**Comment by ChetanGN** [comment]
Hi @incrediblenitin can you please let me know whether you are still facing the same issue?

**Comment by ChetanGN** [comment]
@incrediblenitin Please try with the latest [plugin](https://github.com/razorpay/razorpay-edd/releases/tag/2.1.0). It's working for WP. Please let us know if you still facing the issue.
