### ISSUE TITLE
Product listed in USD but it is taking payment in INR of the same amount

### ISSUE THREAD

**Issue by shazshashank** [razorpay/razorpay-edd#9]
The product is listed as $25 but if selecting Razorpay then it is requesting money 25 Indian Rupees. 

It is of no use if you can't correct this. There is no option to select the currency so that the conversion can take place. 

Any updates on this?

**Comment by vikasprogrammer** [comment]
Same issue happened to me today!

**Comment by ChetanGN** [comment]
@shazshashank @vikasprogrammer Can you please install the <a href="https://github.com/razorpay/razorpay-edd/releases">razorpay-edd </a>new release

**Comment by vikasprogrammer** [comment]
Thanks Chetan. I see webhook support has been added, but the readme.md doesn't say which webhooks should be enabled.

**Comment by ChetanGN** [comment]
@vikasprogrammer Kindly refer the following link for webhook configuration https://razorpay.com/docs/webhooks/
